### PR TITLE
Remove bucklescript

### PR DESCRIPTION
**Pull request by chenglou**

### CODE REVIEW

**Comment by chenglou** [comment]
Fixes #11

@alexfedoseev does your PR look like this? I haven't tested this.

**Comment by alex35mil** [comment]
Looks good to me!

**Comment by chenglou** [comment]
Don't think I've made a syntax mistake in here. Please ping if I did.

**Comment by alex35mil** [comment]
I pulled and tested in dev. All good. I think it can be safely released.

**Comment by alex35mil** [comment]
@chenglou Ping: can you release the new version with this change? The current one overlaps with the `language-rescript` grammar and it prevents `ide` package from working in `res/resi` files.

**Comment by chenglou** [comment]
Done. Ping me if it doesn't work. Thanks.

**Pull request merged**
